In [1]:
# 1. Импортировать NumPy
import numpy as np

In [2]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

# 1.2 найти среднее значение всех элементов массива

# 1.3 найти среднее значение всех элементов для каждой строки   np.mean()
# и добавить как новый столбец

# 1.4 найти сумму значение всех элементов для каждого столбца   np.sum()
# и добавить как новую строку, учитывая результат 1.3

In [3]:
# 1.1 Массив случайных чисел
mass_10_10 = np.random.randint(1, 101, [10, 10], dtype=np.int64)
mass_10_10

array([[56, 11,  5, 90, 57, 96, 54, 78, 62, 52],
       [67, 39, 40, 28, 61, 25, 14, 77, 31, 70],
       [ 7, 10, 40, 30, 10, 27, 15, 25, 85, 95],
       [97, 75, 20, 79, 12, 89, 41, 99, 30, 98],
       [66, 13, 13, 66,  9,  5, 67, 75, 14, 72],
       [70, 58, 36, 71, 91, 52,  2, 13, 96,  3],
       [ 5, 11,  1, 94, 84, 13, 63, 38, 29, 58],
       [20, 20, 30, 60,  8, 50, 17, 96, 81, 61],
       [70, 94, 49, 72, 15, 77, 40, 10, 17,  1],
       [60, 70,  8, 65, 36, 44, 17,  1, 26, 93]], dtype=int64)

In [4]:
## 1.2 Среднее значение всех элементов массива
mass_10_10.mean()

45.93

In [5]:
mass_10_10_13 = mass_10_10.astype(np.float64)

mass_10_10_13 = np.append(mass_10_10_13, mass_10_10.mean(axis = 1).reshape(10,1), axis = 1)
mass_10_10_13

array([[56. , 11. ,  5. , 90. , 57. , 96. , 54. , 78. , 62. , 52. , 56.1],
       [67. , 39. , 40. , 28. , 61. , 25. , 14. , 77. , 31. , 70. , 45.2],
       [ 7. , 10. , 40. , 30. , 10. , 27. , 15. , 25. , 85. , 95. , 34.4],
       [97. , 75. , 20. , 79. , 12. , 89. , 41. , 99. , 30. , 98. , 64. ],
       [66. , 13. , 13. , 66. ,  9. ,  5. , 67. , 75. , 14. , 72. , 40. ],
       [70. , 58. , 36. , 71. , 91. , 52. ,  2. , 13. , 96. ,  3. , 49.2],
       [ 5. , 11. ,  1. , 94. , 84. , 13. , 63. , 38. , 29. , 58. , 39.6],
       [20. , 20. , 30. , 60. ,  8. , 50. , 17. , 96. , 81. , 61. , 44.3],
       [70. , 94. , 49. , 72. , 15. , 77. , 40. , 10. , 17. ,  1. , 44.5],
       [60. , 70. ,  8. , 65. , 36. , 44. , 17. ,  1. , 26. , 93. , 42. ]])

In [6]:
# 1.3 Среднее значение по строкам
mass_10_10.mean(axis = 1).reshape(10,1)

array([[56.1],
       [45.2],
       [34.4],
       [64. ],
       [40. ],
       [49.2],
       [39.6],
       [44.3],
       [44.5],
       [42. ]])

In [8]:
# 1.4 Сумма по столбцам

# pd.set_option('display.width', 120)
# pd.set_option('display.expand_frame_repr', False)
np.append(mass_10_10_13, np.sum(mass_10_10_13, axis = 0).reshape(1,11), axis = 0)

array([[ 56. ,  11. ,   5. ,  90. ,  57. ,  96. ,  54. ,  78. ,  62. ,
         52. ,  56.1],
       [ 67. ,  39. ,  40. ,  28. ,  61. ,  25. ,  14. ,  77. ,  31. ,
         70. ,  45.2],
       [  7. ,  10. ,  40. ,  30. ,  10. ,  27. ,  15. ,  25. ,  85. ,
         95. ,  34.4],
       [ 97. ,  75. ,  20. ,  79. ,  12. ,  89. ,  41. ,  99. ,  30. ,
         98. ,  64. ],
       [ 66. ,  13. ,  13. ,  66. ,   9. ,   5. ,  67. ,  75. ,  14. ,
         72. ,  40. ],
       [ 70. ,  58. ,  36. ,  71. ,  91. ,  52. ,   2. ,  13. ,  96. ,
          3. ,  49.2],
       [  5. ,  11. ,   1. ,  94. ,  84. ,  13. ,  63. ,  38. ,  29. ,
         58. ,  39.6],
       [ 20. ,  20. ,  30. ,  60. ,   8. ,  50. ,  17. ,  96. ,  81. ,
         61. ,  44.3],
       [ 70. ,  94. ,  49. ,  72. ,  15. ,  77. ,  40. ,  10. ,  17. ,
          1. ,  44.5],
       [ 60. ,  70. ,   8. ,  65. ,  36. ,  44. ,  17. ,   1. ,  26. ,
         93. ,  42. ],
       [518. , 401. , 242. , 655. , 383. , 478. , 330. , 512

In [ ]:
# 2. Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули.

In [9]:
np.diag(np.arange(1, 8))

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [ ]:
# 3. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3 и 5 колонки

In [10]:
mass_5_7 = np.random.randint(1, 101, [5, 7])
mass_5_7

array([[87, 78, 80, 67, 90, 15, 37],
       [76, 95, 45, 50, 13, 95, 13],
       [73, 82, 37,  4, 73, 53, 24],
       [77, 38, 71, 90, 96, 57,  7],
       [27, 50, 76, 67, 97, 48, 18]])

In [11]:
#Вариант с удалением колонок
diff_c = mass_5_7[:,2] - mass_5_7[:,4]

clm = np.append(mass_5_7[:,2] -  diff_c, mass_5_7[:,3])
clm_ = np.append(clm, mass_5_7[:,4] +  diff_c).reshape(3,5)

mass_5_7_1 = np.delete(mass_5_7, (2,3,4), 1);

np.insert(mass_5_7_1, (2), clm_, 1)

array([[87, 78, 90, 67, 80, 15, 37],
       [76, 95, 13, 50, 45, 95, 13],
       [73, 82, 73,  4, 37, 53, 24],
       [77, 38, 96, 90, 71, 57,  7],
       [27, 50, 97, 67, 76, 48, 18]])

In [12]:
#Вариант. Прямое обновление.
mass_5_7[:,2] = mass_5_7[:,2] + mass_5_7[:,4]

mass_5_7[:,4] =mass_5_7[:,2] -  mass_5_7[:,4]
mass_5_7[:,2] = mass_5_7[:,2]  -  mass_5_7[:,4]
mass_5_7

array([[87, 78, 90, 67, 80, 15, 37],
       [76, 95, 13, 50, 45, 95, 13],
       [73, 82, 73,  4, 37, 53, 24],
       [77, 38, 96, 90, 71, 57,  7],
       [27, 50, 97, 67, 76, 48, 18]])