## Библиотека numpy - практика

In [2]:
# загрузите необходимые библиотеки
import numpy as np

### Задачи

Решите следующие задачи без использования циклов, с минимальным количеством строк.

1 . Решите следующие небольшие задачи

In [ ]:
# 1.1 создайте список натуральных чисел от 0 до 47

# 1.2 преобразуйте его в матрицу размером 12x4 

# 1.3 преобразуйте эту матрицу в трехмерную матрицу размером 3x4x4



In [35]:
# 1.1 Создание списка
np.arange(48)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [38]:
# Преобразование в массив 12х4
np.arange(48).reshape(12, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [43]:
# Преобразование в массив 3х4х4
mass = np.arange(48).reshape(12, 4)
mass.shape = (3, 4, 4)
mass

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

2 . Американские коллеги прислали архив с наблюдениями температуры, но вот незадача: температура там указана в Фаренгейтах. Формула для перевода: $\frac{C}{5}=\frac{F - 32}{9}$

In [44]:
temps_F = np.array([0, 100, 99.1, 32, 44, 241, 10, 15, 20])
# ваш код здесь
# C = 5/9*(F-32)
def convert_F_to_C(f_value: float) -> float:
  return round(5/9*(f_value-32), 2)

convert = np.vectorize(convert_F_to_C)
temps_C = convert(temps_F)
temps_F_C = np.rec.fromarrays([temps_F, temps_C])

print(temps_F)
print(temps_C)
print("="*40, '\nВ виде кортежей [F, C]')
print(temps_F_C)


[  0.  100.   99.1  32.   44.  241.   10.   15.   20. ]
[-17.78  37.78  37.28   0.     6.67 116.11 -12.22  -9.44  -6.67]
В виде кортежей [F, C]
[(  0. , -17.78) (100. ,  37.78) ( 99.1,  37.28) ( 32. ,   0.  )
 ( 44. ,   6.67) (241. , 116.11) ( 10. , -12.22) ( 15. ,  -9.44)
 ( 20. ,  -6.67)]
